In [0]:
pip install pyspellchecker


     |████████████████████████████████| 1.9MB 2.8MB/s 


In [0]:
pip install compound-word-splitter

  Created wheel for compound-word-splitter: filename=compound_word_splitter-0.4-cp36-none-any.whl size=2565 sha256=8b69d7a16821be7a960d1132b9e7155aee558c0475749613d601ed7c698f0966
  Stored in directory: /root/.cache/pip/wheels/4f/de/38/8898744bbad2093c1d909ad5b95f221e85877c3e96131f09d1
Successfully built compound-word-splitter


In [0]:
pip install autocorrect

     |████████████████████████████████| 1.8MB 3.3MB/s 
  Created wheel for autocorrect: filename=autocorrect-1.2.1-cp36-none-any.whl size=1811167 sha256=d2ec840137c1f5bd9d94c3619e3146c273e8707d608d30f8548055eb407e44b5
  Stored in directory: /root/.cache/pip/wheels/d9/70/a8/0335cc91bbd0e54cfd61269c08ccfa4b4178a1ad3411493936
Successfully built autocorrect


Importing all the required libararies, Data sets, Reference word Pickle File.
Data Sets Include Train, Val, Public and Private Data sets

In [0]:
import pickle
import numpy as np
import numpy
import nltk
import nltk
import string
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.tokenize import word_tokenize
from sklearn.model_selection import GridSearchCV
from nltk import pos_tag
from nltk.corpus import wordnet as wn
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
import pandas as pd
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler
from imblearn.under_sampling import TomekLinks
from sklearn.ensemble import AdaBoostClassifier
from autocorrect import Speller
import re
import unicodedata
import emoji
from nltk.corpus import words
import requests
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalMaxPool1D
from tensorflow.keras.layers import Dropout, Conv1D
from tensorflow.keras.optimizers import Adam


train_tweets = np.load('/content/text_train_tweets.npy')
print (train_tweets.shape)
train_labels =np.load('/content/text_train_labels.npy')
val_tweets = np.load('/content/text_val_tweets.npy')
print (val_tweets.shape)
val_labels = np.load('/content/text_val_labels.npy')
test_tweets = np.load('/content/text_test_public_tweets_rand.npy')
print (type(val_labels))
import pickle
objects=[]
objects.append(pickle.load(open("/content/text_word_to_idx.pkl","rb")))
res = dict((v,k) for k,v in objects[0].items())



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


(7098, 52)
(1460, 52)
<class 'numpy.ndarray'>




*   Merging Train and Vallidation tweets into a single Numpy Array
*   Merging Train and Validation Labels into a single Numpy Array



In [0]:
full_tweets=np.concatenate((train_tweets,val_tweets), axis=0)
full_labels=np.concatenate((train_labels,val_labels), axis=0)



*   Storing Tweets into List. (Combined, Train, Validate, Test)



In [0]:
#random sampling
#numbers to words of train,val
#rus = RandomUnderSampler(sampling_strategy="majority")
#X_tl, y_tl = rus.fit_sample(train_tweets, train_labels)
final_train_tweet= []
for i in train_tweets:
    a = []
    for j in i:
        a.append(res[j])
    final_train_tweet.append(a)
print (len(final_train_tweet))
print (y_tl)

final_val_tweets=[]
for i in val_tweets:
    a = []
    for j in i:
        a.append(res[j])
    final_val_tweets.append(a)

final_test_tweets = []
for i in test_tweets:
    a = []
    for j in i:
        a.append(res[j])
    final_test_tweets.append(a)

full_tweet=[]
for i in full_tweets:
    a=[]
    for j in i:
      a.append(res[j])
    full_tweet.append(a)


7098
[0 0 0 ... 3 3 3]


Installing Packages for Preprocessing.

In [0]:
pip install emoji

     |████████████████████████████████| 51kB 1.9MB/s 
  Created wheel for emoji: filename=emoji-0.5.4-cp36-none-any.whl size=42176 sha256=6f3d167a9e20efe703ca0fbc9f4796ccdb6bdde37049c20eca4772c568ba593b
  Stored in directory: /root/.cache/pip/wheels/2a/a9/0a/4f8e8cce8074232aba240caca3fade315bb49fac68808d1a9c
Successfully built emoji


In [0]:
pip install wordninja

     |████████████████████████████████| 542kB 3.4MB/s 
  Created wheel for wordninja: filename=wordninja-2.0.0-cp36-none-any.whl size=541552 sha256=24a68aaa57b15a96db1f5fffe861d65f463148b87208885552394b1ef932abca
  Stored in directory: /root/.cache/pip/wheels/22/46/06/9b6d10ed02c85e93c3bb33ac50e2d368b2586248f192a2e22a
Successfully built wordninja


In [0]:
pip install pyenchant

     |████████████████████████████████| 61kB 2.1MB/s 


In [0]:
pip install gingerit

In [0]:
import nltk
nltk.download('words')
  

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

# Preprocessing

for Preprocessing of tweets, following methods are considered



*   Lemitization
*   Removal of Stop Words
*   Remval of Punctuation
*   Removing Hashtags from the words (Remove hashtag and seperate word)
*   Convertion of Emoji's to text
*   Spell correction of words







In [0]:

def preprocess(doc):
    emoji_chars = emoji.EMOJI_ALIAS_UNICODE.values()
    tag_map = defaultdict(lambda: wn.NOUN)
    tag_map['J'] = wn.ADJ
    tag_map['V'] = wn.VERB
    tag_map['R'] = wn.ADV
    spell = Speller(lang='en')
    final1 = []
    stopwords_list=(stopwords.words('english'))
    alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                 'u', 'v', 'w', 'x', 'y', 'z', '<START>','<NULL>','<END>','stop' , '"', '<user>']
    punch=list(string.punctuation)
    stopwords_list.extend(alphabets)
    stopwords_list.extend(punch)
    for index, entry in enumerate(doc):
        final_words = []
        word_lemmatized = WordNetLemmatizer()
        for word, tag in pos_tag(entry):
            if word not in stopwords_list:
                if word not in alphabets:
                    word_final = word_lemmatized.lemmatize(word, tag_map[tag[0]])
                    if word_final in emoji_chars:
                      word_final=str(unicodedata.name(word_final)).lower()
                    else:
                      pass

                    tweet = ''.join(re.sub('[^A-Za-z0-9]+', '', word_final))
                    final_words.append(spell(tweet))
        final1.append(final_words)
        
    return final1



Applying Preprocessing for Validation Set

In [0]:
k_val=(preprocess(final_val_tweets))

print(k_val)

[['fume', 'hijacked', 'money', 'move', 'full', 'back', 'poutingface'], ['nightmare', 'dream', 'freedom'], ['can', 'really', 'need', 'get', 'business', 'number', 'second', 'fall', 'soldier', 'tragedy', 'right', 'back', 'hatred', 'potus'], ['kike', 'horny', 'kick', 'nudes', 'girls', 'wearyface', 'horny', 'snap'], ['fuck', 'tag', 'picture', 'family', 'first', 'cut', 'number', 'year', 'ago', 'one'], ['swear', 'interview', 'vampire', 'elongated', 'anyone', 'books', 'horror'], ['sick', 'shit', 'mad', 'angry', 'dead', 'bloody', 'online', 'poutingface', 'poutingface', 'poutingface', 'poutingface'], ['make', 'remover', 'sting', 'relief'], ['despair', 'mouth', 'foam', 'leave', 'camp', 'expose'], ['whose', 'customer', 'love', 'imagine', 'day', 'sing', 'tune', 'call', 'dismal'], ['late', 'hard', 'make', 'manchester', 'day', 'sad'], ['mother', 'nature', 'drop', 'mad', 'beat', 'morning', 'wish', 'would', 'shake', 'shower', 'stall', 'stand', 'naked'], ['cryingface', 'cryingface', 'people', 'want', 'h

Applying Preprocessing for Train Set

In [0]:
k_train=(preprocess(final_train_tweet))

print(k_train)

[['make', 'fuck', 'irate', 'jesus', 'nobody', 'call', 'ppl', 'like', 'aime', 'abusive', 'strawman', 'omao'], ['low', 'adam', 'bull', 'fake', 'outrage'], ['pass', 'away', 'early', 'morning', 'fast', 'furious', 'styled', 'car', 'crash', 'leave', 'at', 'strip', 'club', 'rough', 'stuff'], ['low', 'wow', 'gonna', 'say', 'really', 'haha', 'see', 'chris', 'nah', 'dont', 'even', 'snap', 'anymore', 'dude'], ['need', 'beatbox', 'sushi', 'date', 'iceball', 'spaghetti', 'olive', 'guarded', 'date', 'cheesewedge', 'fistedhandsign', 'emojimodifierfitzpatricktype3', 'rocks', 'date', 'sliceofpizza'], ['republicans', 'namely', 'graham', 'flake', 'sasse', 'others', 'safe', 'wrath', 'hence', 'pillary', 'hiney', 'kissing', 'ad', 'saw'], ['like', 'rabid', 'dog', 'pull', 'back', 'cupboard', 'look', 'bakewellfound', 'french', 'fancied', 'mini', 'batternburg', 'winner'], ['tell', 'racist', 'bigot', 'always', 'resort', 'insult', 'fag', 'like', 'bad', 'racist', 'bigot'], ['follow', 'follow', 'relentless', 'succe

Combining Val and Train Sets

In [0]:
k_full=(preprocess(full_tweet))
print(k_full)

[['make', 'fuck', 'irate', 'jesus', 'nobody', 'call', 'ppl', 'like', 'aime', 'abusive', 'strawman', 'omao'], ['low', 'adam', 'bull', 'fake', 'outrage'], ['pass', 'away', 'early', 'morning', 'fast', 'furious', 'styled', 'car', 'crash', 'leave', 'at', 'strip', 'club', 'rough', 'stuff'], ['low', 'wow', 'gonna', 'say', 'really', 'haha', 'see', 'chris', 'nah', 'dont', 'even', 'snap', 'anymore', 'dude'], ['need', 'beatbox', 'sushi', 'date', 'iceball', 'spaghetti', 'olive', 'guarded', 'date', 'cheesewedge', 'fistedhandsign', 'emojimodifierfitzpatricktype3', 'rocks', 'date', 'sliceofpizza'], ['republicans', 'namely', 'graham', 'flake', 'sasse', 'others', 'safe', 'wrath', 'hence', 'pillary', 'hiney', 'kissing', 'ad', 'saw'], ['like', 'rabid', 'dog', 'pull', 'back', 'cupboard', 'look', 'bakewellfound', 'french', 'fancied', 'mini', 'batternburg', 'winner'], ['tell', 'racist', 'bigot', 'always', 'resort', 'insult', 'fag', 'like', 'bad', 'racist', 'bigot'], ['follow', 'follow', 'relentless', 'succe

Applying Preprocessing for Test Set

In [0]:
k_test=(preprocess(final_test_tweets))
print(k_test)

[['org', 'mother', 'daughter', 'dull', 'ni', 'move', 'dad', 'worry'], ['happy', 'birthday', 'repeated', 'miss', 'excited', 'back', 'florida', 'hear', 'turkey', 'date', 'repeated', 'yellowheads', 'partypopper'], ['ever', 'cry', 'middle', 'bomb', 'rest', 'someone', 'woke', 'emergency', 'sleep', 'cry'], ['mentally', 'suffer', 'worthless', 'pain'], ['courage', 'driver', 'shot', 'bus', 'show', 'courage', 'natural', 'scare', 'death', 'threat', 'make', 'flee', 'fast'], ['org', 'whitefrowningface'], ['labor', 'yet', 'loudlycryingface', 'tiredface'], ['place', 'two', 'whole', 'suppose', 'come', 'together', 'broken', 'sick', 'person', 'terrible'], ['use', 'make', 'peanut', 'butter', 'energy', 'ball', 'time', 'love', 'yummy'], ['post', 'vacation', 'blue', 'real', 'pensiveface'], ['really', 'sad', 'hear', 'terror', 'attack', 'condolence', 'victim', 'family'], ['great', 'workout', 'morning', 'alongside', 'leg', 'still'], ['lose', 'sad', 'tired', 'upset'], ['ever', 'cry', 'middle', 'bomb', 'rest', '



*   De Tokenizing Processed Output, So that it can be given as input    to  TfidVectorizer for Feature Extraction.
*   TreebankWordDetokenizer is used to carry out the operation



In [0]:
k_tweet_test=[]
for k in k_test:
  k_tweet_test.append((TreebankWordDetokenizer().detokenize(k)))
print(k_tweet_test)

k_tweet_train=[]
for k in k_train:
  k_tweet_train.append((TreebankWordDetokenizer().detokenize(k)))
print(k_tweet_train)

k_tweet_val=[]
for k in k_val:
  k_tweet_val.append((TreebankWordDetokenizer().detokenize(k)))
print(k_tweet_val)

k_tweet_full=[]
for k in k_full:
  k_tweet_full.append((TreebankWordDetokenizer().detokenize(k)))
print(k_tweet_full)


['org mother daughter dull ni move dad worry', 'happy birthday repeated miss excited back florida hear turkey date repeated yellowheads partypopper', 'ever cry middle bomb rest someone woke emergency sleep cry', 'mentally suffer worthless pain', 'courage driver shot bus show courage natural scare death threat make flee fast', 'org whitefrowningface', 'labor yet loudlycryingface tiredface', 'place two whole suppose come together broken sick person terrible', 'use make peanut butter energy ball time love yummy', 'post vacation blue real pensiveface', 'really sad hear terror attack condolence victim family', 'great workout morning alongside leg still', 'lose sad tired upset', 'ever cry middle bomb rest someone woke emergency sleep cry', 'watch senator joyful dance step morning get roll dude', 'overcome insane awe emotion son talent cry', 'joyless faith one jesus die joy jesus happiness', 'bad film ever see nothing happen entire film shocking', 'furious make', 'revolt', 'meet either lesson

De Tokenizing Combined Train and Valid Sets.

In [0]:
k =np.concatenate((k_train, k_val), axis=0)
kt=[]
for i in k:
  kt.append((TreebankWordDetokenizer().detokenize(i)))

# Feature Extraction

the product of Term Frequency and Inverse Doucument frequency will give the measure of how frequent the word is in a document multiplied by how unique the word is, giving rise to Term Frequency-Inverse Document Frequency(TF-IDF) measure.


*   Defining Function for Feature Extraction (Dimensionality Reduction/Pattern matching)
*   TfidfVectorizer is used to perform the activity



In [0]:
def vector(data, fulldata):
  vectorizer = TfidfVectorizer (max_features=10000, ngram_range=(1,2), min_df=7, max_df=0.08, stop_words=stopwords.words('english'))
  vectorizer.fit(fulldata)
  vector = vectorizer.transform(data)
  vector_array=vector.toarray()
  return(vector_array)


*   Function For reviewing generated Vocabulary
*   Prediction accuracy can be improved by properly building the vocubulary



In [0]:
def vector_word(data, fulldata):
  vectorizer = TfidfVectorizer(max_features=10000,ngram_range=(1,1), smooth_idf=False , min_df=0.00001, norm='l2', max_df=0.1, binary=True, sublinear_tf=True)
  vectorizer.fit(fulldata)
  vector = vectorizer.transform(data)
  vectorizer.vocabulary_
  vector_array=vector.toarray()
  return(vectorizer.vocabulary_)

Console Output for Vocubalry built for Complete Data Set

In [0]:
whole_dataset_word=vector_word(k_tweet_full,kt)
training_word=vector_word(k_tweet_train,kt)
test_word=vector_word(k_tweet_test,kt)
valid_word=vector_word(k_tweet_val,kt)
print (whole_dataset_word)

{'make': 5197, 'fuck': 3309, 'irate': 4458, 'jesus': 4565, 'nobody': 5893, 'call': 1216, 'ppl': 6641, 'like': 4965, 'aime': 203, 'abusive': 47, 'strawman': 8288, 'omao': 6092, 'low': 5117, 'adam': 102, 'bull': 1145, 'fake': 2977, 'outrage': 6188, 'pass': 6324, 'away': 587, 'early': 2597, 'morning': 5609, 'fast': 3013, 'furious': 3343, 'styled': 8345, 'car': 1272, 'crash': 1904, 'leave': 4876, 'at': 513, 'strip': 8306, 'club': 1572, 'rough': 7362, 'stuff': 8329, 'wow': 9851, 'gonna': 3549, 'say': 7498, 'really': 6977, 'haha': 3734, 'see': 7594, 'chris': 1481, 'nah': 5734, 'dont': 2472, 'even': 2856, 'snap': 7967, 'anymore': 374, 'dude': 2560, 'need': 5794, 'beatbox': 744, 'sushi': 8453, 'date': 2085, 'iceball': 4151, 'spaghetti': 8083, 'olive': 6087, 'guarded': 3692, 'cheesewedge': 1428, 'fistedhandsign': 3115, 'emojimodifierfitzpatricktype3': 2706, 'rocks': 7318, 'sliceofpizza': 7901, 'republicans': 7161, 'namely': 5745, 'graham': 3604, 'flake': 3121, 'sasse': 7472, 'others': 6169, 'sa

Tfidf is applied for all the sets (Train, Validate, Test, Complete)

In [0]:
whole_dataset=vector(k_tweet_full,kt)
training=vector(k_tweet_train,kt)
test=vector(k_tweet_test,kt)
valid=vector(k_tweet_val,kt)

Now as the Data is preprocessed and feature Extraction is applied, We are ready to build the Machine Learning Models.

# Conventional Methods


**Naive Bayes**


*   TF and IDF are based on the probabilty of finding a word in a document, Even Naive Bayes works on the Bayes theorem of probability of finding a word in the document. Because of this, I considered Naive Bayes as the first approach towards building the Model 

**Hyper Parameter Tuning**



*   Although Grid Search CV can be used for finding the best parameters, I have Manually verified by changing the tunable parameters. (Both for TfidfVectorizer and Naive Bayes)

*   After trying different Boosting Algorithms, I have Decided to use AdaBoost. For this, prediction accuracy was good when compared to others.

**Evaluation Accuracy:** 51.78

**Testing Accuracy:** 53.48 (Public Set)






In [0]:
naive = AdaBoostClassifier(naive_bayes.MultinomialNB(alpha=0.01, fit_prior=False), n_estimators=25, random_state=None,learning_rate=0.99, algorithm='SAMME.R')

# naive=naive_bayes.GaussianNB(priors=None, var_smoothing=1e-09)

naive.fit(vector(kt, k_tweet_full), full_labels)
#predictions_NB_train = naive.predict(vector(k_train,k))
#print("training dataset",accuracy_score(predictions_NB_train, a_train_label)*100)

kit=vector(k_tweet_val,kt)
predictions_NB_val = naive.predict(kit)
print("valid dataset",accuracy_score(predictions_NB_val, val_labels)*100)

# predictions_NB_newtweet=naive.predict(vector(k_extratweet,k))
# print("extra tweet", accuracy_score(predictions_NB_newtweet, labelsextra)*100)

kit_test=vector(k_tweet_test,kt)
predictions_NB_test = naive.predict(kit_test)
print (predictions_NB_test)

valid dataset 51.78082191780822
[1 2 1 ... 2 1 2]


After multiple trials and using various algorithms like SVM (gave ~51% evaluation accuracy). Random Forest gave the best Accuracy. 

**Random Forest Classification**

Random forest Classifer gave the better reasults when compared to other classifier, this may be due to the following reasons.


*   Random forest works well for increasing number of samples(Vocabulary)


*   Random Forest will be less prone to overfitting and gives a more generalized prediction.



*   Moreover, Naive Bayes has a assumption of all features being independent which is mostly untrue in real time scenarios.

**Hyper Parameter Tuning**

GridSearchCV is used in order to find out the best parameters for random forest. It really took a lot of time to give the best parameters (nearly 2.5 hours). This is because, Many parameters are availabe for tuning(Different combinations are searched).

**Evaluation Accuracy:** 60.95

**Testing Accuracy:** 58.932 (Public Set), 64.270 (private set)




In [0]:
p={'max_depth':[3,5,10,None],
              'n_estimators':[10,100,200,300,400,500],
               'criterion':['gini','entropy'],
               'bootstrap':[True,False]
              }

#r = RandomForestClassifier(n_estimators=200,random_state=0)
rfc=RandomForestClassifier()
r = GridSearchCV(RandomForestClassifier(rfc,p, cv=5))
r.fit(vector(kt, k_tweet_full), full_labels)

kit=vector(k_tweet_val,kt)
predictions_NB_val = r.predict(kit)
print("valid dataset",accuracy_score(predictions_NB_val, val_labels)*100)

# predictions_NB_newtweet=naive.predict(vector(k_extratweet,k))
# print("extra tweet", accuracy_score(predictions_NB_newtweet, labelsextra)*100)

kit_test=vector(k_tweet_test,kt)
predictions_NB_test = r.predict(kit_test)
print (predictions_NB_test)


valid dataset 60.95890410958904
[3 2 1 ... 2 1 0]


# Deep Learning Method



*   For Implementing Deep learning method, A Sequential model with 2 hidden layers are Selected.
*   Evaluation Accuracy for this is 44.1%





In [0]:
def cnn(X_train, y_train):
    features = 10000
    drop = 0.1
    epoch = 5
    model_nn = Sequential()
    model_nn.add(Conv1D(128, 5, activation='relu'))
    model_nn.add(GlobalMaxPooling1D())
    model_nn.add(Dense(512, input_shape=(features,), activation='softmax'))
    model_nn.add(Dropout(drop))
    model_nn.add(Dense(256, activation='sigmoid'))
    model_nn.add(Dropout(drop))
    model_nn.add(Dense(4, activation='sigmoid'))

    
    optimizer = Adam(lr=0.003, beta_1=0.9, beta_2=0.999, epsilon=None, 
                                      decay=0.0, amsgrad=False, clipnorm=1)
    model_nn.compile(loss='sparse_categorical_crossentropy',
                 optimizer=optimizer,
                 metrics=['accuracy'])
    model_nn.fit(X_train_mod, y_train,
                 batch_size=1,
                 epochs=epoch,
                 verbose=1,
                 validation_split=0.1,
                 shuffle=True)
    return model_nn

In [0]:
vectorizer = TfidfVectorizer (max_features=10000, ngram_range=(1,2), min_df=7, max_df=0.08, stop_words=stopwords.words('english'))
m=cnn(vector(k_tweet_train, kt), full_labels)

In [0]:
prediction=m.predict(vector(k_tweet_val, kt))
print(type(prediction))
print(prediction)
labels = [0,1,2,3]
sentiments = [labels[np.argmax(pred)] for pred in prediction]
sentiments=np.array(sentiments)
print((sentiments))

<class 'numpy.ndarray'>
[[8.4272808e-01 2.5129534e-04 1.9117590e-07 2.9608383e-04]
 [1.4977683e-08 4.4257587e-01 2.4161341e-07 1.0181168e-06]
 [4.7694473e-03 2.4999005e-03 1.0470114e-05 8.4545856e-05]
 ...
 [9.0845019e-01 1.7515889e-04 5.5790292e-07 1.7749547e-03]
 [1.4473908e-07 7.1431845e-02 2.8345121e-05 3.0143141e-05]
 [2.3050200e-02 1.7697377e-03 1.0183150e-02 7.9269511e-01]]
[0 1 0 ... 0 1 3]


In [0]:
print("valid dataset",accuracy_score(sentiments, val_labels)*100)

valid dataset 44.109589041095894


# Observations


*   I got, Eval Accuracy for Deep Learning low when comapred to Conventional Model. This May be due to CNN works better for Image Classification. reason to adopt CNN in image analysis and classification is due to CNN can extract an area of features and predict relationship among them. When Consider twitter Data, Data Input is given From Tfidf, So there is a chance of Predicting Wrong Relationship between words (Hence, May predict wrong Sentiment).
*   After Seeing the final Results, I felt that the model can be improved if considered few more parameters like Handling Un balanced class labels. In our Case Count Of labels 1,2,3,4 is not of equal Weights. If sampling is done for Majority class labels, Accuracy May Improve.

*   Data can be cleaned furthur, as i saw some noise even after preprocessing on final test set.


